version: '3'

networks:
  redis_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.81.0/24
        # - subnet: 192.168.1.0/24
          # gateway: 192.168.1.1

services:
  redis_master:
    image: redis
    container_name: redis_master
    ports:
      - "6379:6379"
    volumes:
      - ./master/conf:/usr/local/etc/redis
      # - ./master/data:/data
      - ./master/entrypoint.sh:/entrypoint.sh
    command: redis-server /usr/local/etc/redis/redis.conf
    # environment:
    #   - REDIS_PORT=6379
    # entrypoint: ["/entrypoint.sh"]
    # restart: always
    # network_mode: "host"
    # networks:
    #   - redis_net
    networks:
      redis_net:
        ipv4_address: 192.168.81.10
        # ipv4_address: 192.168.1.10

  redis_slave_1:
    image: redis
    container_name: redis_slave_1
    ports:
      - "6380:6380"
    volumes:
      - ./slave/conf:/usr/local/etc/redis
      # - ./slave/data:/data
      - ./slave/entrypoint.sh:/entrypoint.sh
    command: redis-server /usr/local/etc/redis/redis-1.conf
    # environment:
    #   - REDIS_PORT=6380
    # entrypoint: ["/entrypoint.sh"]
    # restart: always
    # network_mode: "host"
    # networks:
    #   - redis_net
    networks:
      redis_net:
        ipv4_address: 192.168.81.11

  redis_slave_2:
    image: redis
    container_name: redis_slave_2
    ports:
      - "6381:6381"
    volumes:
      - ./slave/conf:/usr/local/etc/redis
      # - ./slave/data:/data
      - ./slave/entrypoint.sh:/entrypoint.sh
    command: redis-server /usr/local/etc/redis/redis-2.conf
    # environment:
    #   - REDIS_PORT=6381
    # entrypoint: ["/entrypoint.sh"]
    # restart: always
    # network_mode: "host"
    # networks:
    #   - redis_net
    networks:
      redis_net:
        ipv4_address: 192.168.81.12

  redis_sentinel_1:
    image: bitnami/redis-sentinel:latest
    container_name: redis_sentinel_1
    environment:
      # - REDIS_MASTER_HOST=192.168.65.1
      - REDIS_MASTER_HOST=192.168.81.10
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=redis_master
      - REDIS_SENTINEL_PORT_NUMBER=26379
      - REDIS_SENTINEL_QUORUM=2
    ports:
      - "26379:26379"
    depends_on:
      - redis_master
      - redis_slave_1
      - redis_slave_2
    # restart: always
    # network_mode: "host"
    # networks:
    #   - redis_net
    networks:
      redis_net:
        ipv4_address: 192.168.81.13

  redis_sentinel_2:
    image: bitnami/redis-sentinel:latest
    container_name: redis_sentinel_2
    environment:
      # - REDIS_MASTER_HOST=192.168.65.1
      - REDIS_MASTER_HOST=192.168.81.10
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=redis_master
      - REDIS_SENTINEL_PORT_NUMBER=26380
      - REDIS_SENTINEL_QUORUM=2
    ports:
      - "26380:26380"
    depends_on:
      - redis_master
      - redis_slave_1
      - redis_slave_2
    # restart: always
    # network_mode: "host"
    # networks:
    #   - redis_net
    networks:
      redis_net:
        ipv4_address: 192.168.81.14

  redis_sentinel_3:
    image: bitnami/redis-sentinel:latest
    container_name: redis_sentinel_3
    environment:
      # - REDIS_MASTER_HOST=192.168.65.1
      - REDIS_MASTER_HOST=192.168.81.10
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=redis_master
      - REDIS_SENTINEL_PORT_NUMBER=26381
      - REDIS_SENTINEL_QUORUM=2
    ports:
      - "26381:26381"
    depends_on:
      - redis_master
      - redis_slave_1
      - redis_slave_2
    # restart: always
    # network_mode: "host"
    # networks:
    #   - redis_net
    networks:
      redis_net:
        ipv4_address: 192.168.81.15